'use strict';

/**
 * Translate PostgreSQL errors caused by bad input into client errors
 * (Security Hardening Phase 3).
 *
 * ── What was wrong ───────────────────────────────────────────────────────────
 * Active testing found that a range of ordinary hostile inputs — a 4,000
 * character name, a null byte in a string, an out-of-range payment amount, an
 * impossible date like 2026-02-31 — reached PostgreSQL, raised a constraint or
 * type error, and were reported to the caller as **HTTP 500**.
 *
 * No data leaked (the response bodies are generic), but 500 is the wrong
 * answer and has real consequences:
 *
 *   - It tells an attacker which inputs reach the database and which are
 *     filtered, which is exactly the feedback loop error-based probing needs.
 *   - It is indistinguishable from a genuine server fault, so real incidents
 *     are buried in noise generated by anyone sending junk.
 *   - Clients cannot tell "fix your input" from "retry later".
 *
 * ── Why the mapping lives here ───────────────────────────────────────────────
 * Per-field validation for every column of 35 tables would be a large surface
 * to write and a larger one to keep in step with the schema. The database
 * already knows precisely which inputs it will not accept, and says so with a
 * standard SQLSTATE code. Translating those codes covers the whole class
 * consistently, including columns added later.
 *
 * This complements up-front validation rather than replacing it: ownership,
 * format and range checks still run first where they exist, and this catches
 * what reaches the database anyway.
 *
 * ── Messages are deliberately vague ──────────────────────────────────────────
 * The driver's own message names the column, its type and its width
 * (`value too long for type character varying(100)`). That is schema
 * disclosure, so it is logged and never returned.
 */

/** SQLSTATE → [HTTP status, client-safe message] */
const CLIENT_ERROR_CODES = {
  22001: [400, 'A submitted value is too long.'],
  22003: [400, 'A numeric value is out of range.'],
  22007: [400, 'A date or time value is not valid.'],
  22008: [400, 'A date or time value is out of range.'],
  22021: [400, 'A submitted value contains invalid characters.'],
  '22P02': [400, 'A submitted value has an invalid format.'],
  23502: [400, 'A required value is missing.'],
  23503: [400, 'A referenced record does not exist.'],
  23505: [409, 'That record already exists.'],
  23514: [400, 'A submitted value is not allowed.'],
};

/**
 * @param {unknown} err
 * @returns {{status: number, error: string}|null} null when the error is not
 *   attributable to client input — those must stay 500s.
 */
const classifyDbError = (err) => {
  const code = err && err.code;
  const mapped = code && CLIENT_ERROR_CODES[code];
  if (!mapped) return null;
  return { status: mapped[0], error: mapped[1] };
};

/**
 * Answer with the translated client error if this error is one, and report
 * whether it did — so a catch block reads:
 *
 *     } catch (e) {
 *       if (sendDbClientError(res, e)) return;
 *       console.error(e);
 *       res.status(500).json({ error: 'Server error' });
 *     }
 *
 * @param {import('express').Response} res
 * @param {unknown} err
 * @returns {boolean} true when a response was sent
 */
const sendDbClientError = (res, err) => {
  const classified = classifyDbError(err);
  if (!classified) return false;
  // Logged with the driver's detail, answered without it.
  console.warn(`[db] client input rejected (${err.code}): ${err.message}`);
  if (!res.headersSent) res.status(classified.status).json(classified);
  return true;
};

module.exports = { classifyDbError, sendDbClientError, CLIENT_ERROR_CODES };
